name: foodrandom
description: A new Flutter project.
publish_to: 'none'

version: 1.0.5+1001

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  flutter_launcher_icons: ^0.13.1
  rxdart: ^0.27.7
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/mocks/menu.json

